### ISSUE TITLE
glangValidator crash while compiling and linking shaders

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/glslang#2495] opened 2020-12-31 08:03 UTC
I can reproduce a crash while compiling and linking with glangValidator vesion "10:11.0.0" (included in lunar sdk 1.2.162.0) and with a direct checkout from master. Could not reproduce with the one from 1.2.154.1 (glangValidator -v returns the same version somehow). When compiling from C++, the crash happens deep inside "glslang::GlslangToSpv".

`glslangValidator.exe a.vs b.vs c.vs -V -S vert -o a.spv`

I've put the three sources here:
https://gist.github.com/FilippoLeon/27ad5da7cbda1cdfd27ef35ad2d32df7

(I tried to strip down as much as possible to the point where removing a few variable just stops the crash)

**Comment by greg-lunarg** [comment] 2020-12-31 18:37
Thanks. Looking at it now...

**Comment by johnkslang** [comment] 2021-01-04 18:13
There are some known issues in play regarding linking together variables from multiple compilation units into the same stage for downstream consumption.  I'm failing to find the active issue right now, but want to before anyone spends too much time debugging the AST -> SPIR-V step before realizing the AST itself might have been linked incorrectly.

**Comment by johnkslang** [comment] 2021-01-05 18:15
I couldn't find the issue because it's just the PR #2458.  I think it should be completed first, unless you see this is definitely independent.

**Comment by ShchchowAMD** [comment] 2021-01-06 03:00
Meeting some regression when change id system to 64bit during testing, will update this week (I'd also try to fix this issue).

**Comment by ShchchowAMD** [comment] 2021-01-24 04:42
@FilippoLeon  would you mind to try again with #2458 PR please? Local test observed no crash now with case attached here.

**Comment by FilippoLeon** [comment] 2021-01-26 12:56
Yes, it is working also with a complete version of the shader posted above. Thank you.

**Comment by greg-lunarg** [comment] 2021-02-12 23:34
Fixed by #2458.

**Comment by greg-lunarg** [comment] 2021-02-16 08:17
#2458 Merged

**Closed by greg-lunarg** 2021-02-16 08:17 UTC
Labels: GLSL/ESSL, Linker, SPIR-V, bug
