### ISSUE TITLE
standalone, preprocesser: Want to be able to add #defines as command line

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#493] opened 2016-08-30 21:23 UTC
For production, equiv compiler functionality which is typically -D or /D for most compilers/cmake to include preprocessor macros. It's sort of hard to integrate glsllang standalone into a production pipe without it because there are a few things we need to #define for the GLSLang path. I also didn't see a parameter for the preprocessor function that allowed macros to be defined as additional inputs, so didn't seem easy to extend the standalone to do this.

It might also be useful to have a built-in preprocess for glslangvalidator, (maybe this exists already?) Something like _VULKAN or _SPIRV or something to identify to the preprocessor that this is being compiled by GLSLlang.

**Comment by johnkslang** [comment] 2016-08-30 22:32
This is a duplicate of issue #87.

**Closed by johnkslang** 2016-08-30 22:32 UTC
Labels: duplicate
