### ISSUE TITLE
Crash parsing built-in structures

### ISSUE THREAD

**Issue by sigint9** [KhronosGroup/glslang#837] opened 2017-04-14 21:58 UTC
while parsing the built-in structure declaration for gl_DepthRangeParameters the parser encounters struct_specifier for which it creates a new TType and calls into parseContext.structArrayCheck() (line 2364 in glslang.y). The structure list is not properly initialized and this function crashes as it tries to walk the list.

the parser is called like this:

```
  Shader shader;
  const char* test[] = {"precision highp float;\n#line 1\n", shaderCode.c_str()};
  shader.setStrings(test, 2);

  TBuiltInResource resources;
  memset(&resources, 0, sizeof(resources));
  resources.limits.nonInductiveForLoops = true;

  shader.parse(&resources, 100, true, EShMsgDefault);
```

**Comment by johnkslang** [comment] 2017-04-18 21:12
Does this happen with stock glslang, or only a modified form of it?

**Comment by sigint9** [comment] 2017-04-18 22:59
@johnkslang this was with the unmodified HEAD from 4 days ago

**Comment by johnkslang** [comment] 2017-05-20 20:32
Still not sure I understand this.

You are compiling ES shaders without using a #version, and falling back on 100 as the default?  

> while parsing the built-in structure declaration for gl_DepthRangeParameters the parser encounters struct_specifier for which it creates a new TType

It creates it with `TType(TTypeList* userDef, const TString& n)`, the constructor that takes the list of structure members, as is done with all structure creations.

The following works for me, from a file.  Can you reproduce this with a file and the standalone glslangValidatior executable?

```
precision highp float;
#line 1
void main()
{
    gl_DepthRange.far;
}
```

Gives the AST

```
Shader version: 100
0:? Sequence
0:1  Function Definition: main( ( global void)
0:1    Function Parameters:
0:1    Sequence
0:1      far: direct index for structure ( global highp float)
0:1        'gl_DepthRange' ( uniform structure{ global highp float near,  global highp float far,  global highp float diff})
0:1        Constant:
0:1          1 (const int)
0:?   Linker Objects
```

**Comment by sigint9** [comment] 2017-05-20 22:37
I fixed the issue by reverting to an old version of glslang. I can't provide any more details about it at the moment, I'm afraid.

**Comment by johnkslang** [comment] 2017-05-20 23:02
Will close this one, and when there is a fresh need (and full example to reproduce), open a new one, and will fix the reproducible issue at that time.

**Closed by johnkslang** 2017-05-20 23:02 UTC
Labels: question
