### ISSUE TITLE
glslang doesn't enforce GLSL linking rules

### ISSUE THREAD

**Issue by weifengz** [KhronosGroup/glslang#296] opened 2016-05-18 23:17 UTC
This simple pair of shaders should have failed to generate spv with linking option due to mismatched uniform blocks, but SPV was generated successfully.

FS:
#version 310 es
precision highp float;
layout(location = 0) out vec4 color;
layout(set = 0, binding = 0) uniform myUBO {
  vec4 base;
};
void main()
{
  color = base + 1.0;
}

VS:
#version 310 es
layout (set = 0, binding = 1) uniform myUBO {
  mat4 m;
};
void main()
{
  gl_Position = m[1];
}

**Comment by johnkslang** [comment] 2016-05-18 23:42
Note glslang is not yet a link-time validator, only a compile-time validator.

This is a duplicate of issue #89.

**Comment by johnkslang** [comment] 2016-08-12 23:45
Transferring comment over to #89.

**Closed by johnkslang** 2016-08-12 23:45 UTC
Labels: duplicate, GLSL/ESSL, Missing Functionality
