### ISSUE TITLE
[HLSL] Not flattening vertex output / fragment input causes compilation failure in Vulkan

### ISSUE THREAD

**Issue by sergeyreznik** [KhronosGroup/glslang#662] opened 2017-01-06 17:36 UTC
Introduced in commit ddfbbe2 (merging pull request #632), method:
`bool HlslParseContext::shouldFlatten(const TType& type) const` (hlslParseHelper.cpp, lines 976-980)

Produces Vulkan validation layer error:
**SC : Type mismatch on location 0.0: 'ptr to output struct of (vec2 of float32)' vs 'ptr to input struct of (vec4 of float32, vec2 of float32)'**

Looks like vertex shader output is being bound to vertex shader input.

My HLSL input looks like:
```
struct VSInput 
{
float3 position : POSITION;
float2 texCoord0 : TEXCOORD0;
};

Texture2D < float4 > baseColorTexture : register(t0, space1);
SamplerState baseColorSampler : register(s16, space1);

struct VSOutput
{
 float4 position : SV_Position;
 float2 texCoord0 : TEXCOORD0;
};

VSOutput vertexMain(VSInput vsIn)
{
 VSOutput vsOut;
 vsOut . texCoord0 = vsIn . texCoord0;
 vsOut . position = float4(vsIn . position, 1.0);
 return vsOut;
}

float4 fragmentMain(VSOutput fsIn): SV_Target0
{
 return baseColorTexture . Sample(baseColorSampler, fsIn . texCoord0);
}
```

Either I'm missing something, or this really fails to compile into valid SPIR-V. Please advice.

**Comment by johnkslang** [comment] 2017-01-06 19:48
I don't think in/out got mixed up: isn't this a cross-stage error, comparing the output of the vertex stage to the input of the fragment stage?

It looks like the problem is SV_Position is recognized as a **Position** built-in on output of the vertex stage and got split off, but not a **FragCoord** built-in on input to the fragment stage, or at least not split off there, so the interfaces don't match.

**Comment by steve-lunarg** [comment] 2017-01-07 00:06
@johnkslang suggested that the right approach is to treat members as built-ins if they would be so in any stage, so the post-flattened or split structure will match.

I can create a PR for that next week.

**Comment by johnkslang** [comment] 2017-01-07 00:09
Indeed, I think that suggestion might apply to a case like SV_IsFrontFace, but in this specific example, if SV_Position is **Position** in one stage and **FragCoord** in another, then both stages see *a* built-in, so there might be more going on.

**Comment by steve-lunarg** [comment] 2017-01-07 01:14
That's a good point.  And in fact, we aren't splitting off FragCoord, so that explains the symptom.  (Seems like we should be).

But maybe there are still asymmetries, where something would be a builtin on one side with no analog on the other?

**Comment by sergeyreznik** [comment] 2017-01-07 11:31
Thank you for the investigation. So, looks like this is really a problem. 

The next question: what should I do now? Shaders are not compiling anymore. The obvious workaround is to locally revert changes to make flattening happen. Or can something be changed in shaders source code to prevent such error?

**Comment by steve-lunarg** [comment] 2017-01-07 16:13
Hi Sergeyreznik,

I added FragCoord to the list of split builtins in #664.  Could you see if that fixes your symptom?

That is just an experimental branch, and by no means meant to be a complete fix, but it would be good to verify that it does address your symptom, and then a complete fix can be built from there.

It's not clear to me why every builtin should not be in the list, in addition to looking across stages as in @johnkslang's suggestion above.

**Comment by sergeyreznik** [comment] 2017-01-07 17:51
@steve-lunarg yes, that fixes a problem

**Comment by steve-lunarg** [comment] 2017-01-08 05:15
Great, thanks for trying it.  I'll get it turned into a real fix next week.

**Comment by steve-lunarg** [comment] 2017-01-09 21:39
There's a complete solution pushed to #664 now.  It's still marked WIP, if anyone would like to check it against local workloads.  I'll remove the WIP after feedback.

The fix packages per-vertex builtins (Position/PointSize/ClipDistance/CullDistance) for non-fragment stages into an interface block.  Do people have workloads with mismatched interfaces between stages?  An example would be: a stage that outputs 2 of those, linked to a stage that inputs just 1 of them.

**Comment by johnkslang** [comment] 2017-02-02 22:32
Fix from 3 weeks ago seems good, closing.

**Closed by johnkslang** 2017-02-02 22:32 UTC
Labels: bug, HLSL
