### ISSUE TITLE
Releases are containing only source code.

### ISSUE THREAD

**Issue by Raffaello** [KhronosGroup/glslang#3457] opened 2023-12-18 09:32 UTC
the only binaries are in the `main-tot`. 
is this related to the latest release? or it could be even a not released version?

If wanting to download not the latest version is not possible.

Would it be possible to attach to each release the binaries too?
It would be a lot simpler to manage the tool versioning and retrieve the right compiled code, avoiding to compiling it from the source.

**Comment by ncesario-lunarg** [comment] 2023-12-18 16:54
This should be fixed as soon as https://github.com/KhronosGroup/glslang/pull/3456 is merged.

**Comment by ncesario-lunarg** [comment] 2023-12-18 19:16
Latest deployment job was successful.

**Comment by Raffaello** [comment] 2023-12-18 21:40
@ncesario-lunarg apologies.
What i ment was to attach the binaries here for e.g.: https://github.com/KhronosGroup/glslang/releases/tag/13.1.1
instead there is only the source code.

rather than having always the "latest" version from main branch here: https://github.com/KhronosGroup/glslang/releases/tag/main-tot

**Comment by ncesario-lunarg** [comment] 2023-12-19 18:14
@Raffaello I agree, that makes more sense to me as well. I believe the `main-tot` tag and having binaries attached to it is necessary, but I can't recall for what (@jeremy-lunarg might know). I think what your requesting will be covered in https://github.com/KhronosGroup/glslang/issues/48; or, at least the change I have in progress to resolve that issue would get you what you want. I'm going to close this as a duplicate of #48. I'm happy to re-open if I misunderstood.

**Closed by ncesario-lunarg** 2023-12-19 18:14 UTC
