### ISSUE TITLE
[VS2013 SP5] ShaderLang.h IncludeResult warning prevents compilation when warnings are treated as erorrs

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#351] opened 2016-06-24 18:39 UTC
I get the following warnings preventing me from compiling with the latest ShaderLang.h

1>h:\dev\source2\main\src\thirdparty\glslang\glslang\public\shaderlang.h(340): error C2220: warning treated as error - no 'object' file generated
1>h:\dev\source2\main\src\thirdparty\glslang\glslang\public\shaderlang.h(340): warning C4510: 'glslang::TShader::Includer::IncludeResult' : default constructor could not be generated
1>          h:\dev\source2\main\src\thirdparty\glslang\glslang\public\shaderlang.h(325) : see declaration of 'glslang::TShader::Includer::IncludeResult'
1>h:\dev\source2\main\src\thirdparty\glslang\glslang\public\shaderlang.h(340): warning C4610: struct 'glslang::TShader::Includer::IncludeResult' can never be instantiated - user defined constructor required

The problem is that IncludeResult has const members which would need to be initialized by a default constructor.  One possible fix would be to do this:

```
        struct IncludeResult {
            // For a successful inclusion, the fully resolved name of the requested
            // include.  For example, in a filesystem-based includer, full resolution
            // should convert a relative path name into an absolute path name.
            // For a failed inclusion, this is an empty string.
            std::string file_name;
            // The content and byte length of the requested inclusion.  The
            // Includer producing this IncludeResult retains ownership of the
            // storage.
            // For a failed inclusion, the file_data
            // field points to a string containing error details.
            const char* file_data;
            size_t file_length;
            // Include resolver's context.
            void* user_data;
        };
```

**Comment by baldurk** [comment] 2016-06-24 18:52
Dupe of #283 ? :smile:

**Comment by danginsburg** [comment] 2016-06-24 19:02
Hah, I thought I'd run into this before.  Can it be fixed this time? ;)

**Comment by johnkslang** [comment] 2016-08-05 23:14
I did a warning purging pass through glslang back on July 8, with commit 7f349c73dbf692e59ca806ed7ed22f4940732355, and some others around that time, which addressed these, but didn't connect them to this issue #.  It added a real constructor, disabled the default constructor, etc.

@danginsburg is this all working for you okay now?  Thanks.

**Comment by danginsburg** [comment] 2016-08-10 00:07
@johnkslang I will need to pull it into our build system to check for sure, which I may not have a chance to do for a bit.  If you don't see these warnings building under VS2013 (and did before), then it's probably fine and the issue can be closed.  Or, if you want, just close the issue and if I see the warnings again I can reopen.

**Comment by johnkslang** [comment] 2016-08-10 00:47
@danginsburg I definitely fixed a good set of these, it's just that time passed.  I see nothing with 2013 right now.

>  just close the issue and if I see the warnings again I can reopen.

That's probably just ongoing standard operation for multiple environments to occasionally report currently needed build improvements, so I'll go with that, thanks.

**Closed by johnkslang** 2016-08-10 00:47 UTC
Labels: bug, Infrastructure
