### ISSUE TITLE
HLSL: Does this shader have a mismatched return type and function type?

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#464] opened 2016-08-14 19:42 UTC
I had to hack it up to change the language from HLSL to unknown, but I see this message on this SPIRV output;

SC (ERROR): object: 0x0 type: 0 location: 8648 msgCode: 5: SPIR-V module not valid: OpReturnValue Value <id> '26's type does not match OpFunction's return type

I don't understand the SPIRV syntax well enough. It looks to me like the function is declared to have a return type of VSOut in lines 10 and 11. Though, is input supposed to list before output?

```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 43

                              Capability Shader
                              Capability SampledBuffer
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "PosShader"
                              Name 4  "PosShader"
                              Name 9  "VSOut"
                              MemberName 9(VSOut) 0  "fPos"
                              MemberName 9(VSOut) 1  "fTex"
                              Name 13  "ColorShader(struct-VSOut-vf4-vf21;"
                              Name 12  "Input"
                              Name 15  "Out"
                              Name 32  "SS_DEFAULT"
                              Name 33  "SS_DEFAULT_CLAMP"
                              Name 34  "SS_ANISO"
                              Name 35  "SS_ANISO_CLAMP"
                              Name 36  "SS_POINT"
                              Name 37  "SS_POINT_CLAMP"
                              Name 41  "V_Position"
                              Name 42  "V_TexCoord"
                              Decorate 32(SS_DEFAULT) DescriptorSet 0
                              Decorate 32(SS_DEFAULT) Binding 0
                              Decorate 33(SS_DEFAULT_CLAMP) DescriptorSet 0
                              Decorate 33(SS_DEFAULT_CLAMP) Binding 1
                              Decorate 34(SS_ANISO) DescriptorSet 0
                              Decorate 34(SS_ANISO) Binding 2
                              Decorate 35(SS_ANISO_CLAMP) DescriptorSet 0
                              Decorate 35(SS_ANISO_CLAMP) Binding 3
                              Decorate 36(SS_POINT) DescriptorSet 0
                              Decorate 36(SS_POINT) Binding 4
                              Decorate 37(SS_POINT_CLAMP) DescriptorSet 0
                              Decorate 37(SS_POINT_CLAMP) Binding 5
                              Decorate 41(V_Position) DescriptorSet 0
                              Decorate 41(V_Position) Binding 0
                              Decorate 42(V_TexCoord) DescriptorSet 0
                              Decorate 42(V_TexCoord) Binding 1
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypeVector 6(float) 2
        9(VSOut):             TypeStruct 7(fvec4) 8(fvec2)
              10:             TypePointer Function 9(VSOut)
              11:             TypeFunction 7(fvec4) 10(ptr)
              16:             TypeInt 32 1
              17:     16(int) Constant 0
              18:    6(float) Constant 0
              19:    7(fvec4) ConstantComposite 18 18 18 18
              20:             TypePointer Function 7(fvec4)
              22:     16(int) Constant 1
              23:    8(fvec2) ConstantComposite 18 18
              24:             TypePointer Function 8(fvec2)
              30:             TypeSampler
              31:             TypePointer UniformConstant 30
  32(SS_DEFAULT):     31(ptr) Variable UniformConstant
33(SS_DEFAULT_CLAMP):     31(ptr) Variable UniformConstant
    34(SS_ANISO):     31(ptr) Variable UniformConstant
35(SS_ANISO_CLAMP):     31(ptr) Variable UniformConstant
    36(SS_POINT):     31(ptr) Variable UniformConstant
37(SS_POINT_CLAMP):     31(ptr) Variable UniformConstant
              38:             TypeImage 6(float) Buffer sampled format:Unknown
              39:             TypeSampledImage 38
              40:             TypePointer UniformConstant 39
  41(V_Position):     40(ptr) Variable UniformConstant
  42(V_TexCoord):     40(ptr) Variable UniformConstant
    4(PosShader):           2 Function None 3
               5:             Label
         15(Out):     10(ptr) Variable Function
              21:     20(ptr) AccessChain 15(Out) 17
                              Store 21 19
              25:     24(ptr) AccessChain 15(Out) 22
                              Store 25 23
              26:    9(VSOut) Load 15(Out)
                              ReturnValue 26
                              FunctionEnd
13(ColorShader(struct-VSOut-vf4-vf21;):    7(fvec4) Function None 11
       12(Input):     10(ptr) FunctionParameter
              14:             Label
                              ReturnValue 19
                              FunctionEnd
```

Which I created with this simple shader

```
#pragma warning( disable : 3078 )
 #pragma warning( disable : 3571 )
 #pragma warning( disable : 3550 )
 #pragma warning( disable : 4008 )
 
sampler SS_DEFAULT       : register(s0);
sampler SS_DEFAULT_CLAMP : register(s1);
sampler SS_ANISO         : register(s2);
sampler SS_ANISO_CLAMP   : register(s3);
sampler SS_POINT         : register(s4);
sampler SS_POINT_CLAMP   : register(s5);

//ResourceSet VertexData 
    Buffer<float3> V_Position : register(t0);
    Buffer<float2> V_TexCoord : register(t1);
//EndTexture Set
#line  12 "D:/p4/OxideHaswell/Main/Apps/GraphicsTest/TestShaders.oxsl"
    // -----------------------------------------------------------------------
    struct VSOut
    {
        float4 fPos    : SV_POSITION;
		float2 fTex	   : TEXCOORD;
    };


    // -----------------------------------------------------------------------
    VSOut PosShader( uint VertexID : SV_VertexID )
    {
        VSOut Out;
		Out.fPos = 0;
		Out.fTex = 0;
        return Out;
    }


    float4 ColorShader( VSOut Input ) : SV_TARGET0
    {
		return float4(0,0,0,0);
    }

```

**Comment by johnkslang** [comment] 2016-08-17 16:57
I see in your SPIR-V dump the mismatch (returning VSOut object, but return type is void).

However, when I try that shader, I get this:

```
ERROR: 0:14: 'vector size not yet supported in texture type' : Expected
ERROR: 1 compilation errors.  No code generated.
```

If I comment out the Buffer<floatN> lines, I get the correct match between the return object and function type:

```
14(PosShader(u1;):   11(VSOut) Function None 12
    13(VertexID):      7(ptr) FunctionParameter
              15:             Label
         21(Out):     16(ptr) Variable Function
              27:     26(ptr) AccessChain 21(Out) 23
                              Store 27 25
              31:     30(ptr) AccessChain 21(Out) 28
                              Store 31 29
              32:   11(VSOut) Load 21(Out)
                              ReturnValue 32
                              FunctionEnd
```

So, I'm completely not reproducing what's going on.

**Comment by dankbaker** [comment] 2016-08-17 17:58
That's odd, I'll try to get latest and see what happens.

**Comment by johnkslang** [comment] 2016-09-03 02:31
This was a duplicate of the problem of entry points being declared void, now fixed.

**Closed by johnkslang** 2016-09-03 02:31 UTC
Labels: HLSL, question
