### ISSUE TITLE
HLSL: Invalid SPIR-V when accessing < 4 component images or buffers

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#1340] opened 2018-04-09 13:42 UTC
I am running into a significant number of issues with HLSL -> SPIR-V using latest glslang (optimizer enabled, as well) - VK SDK 1.70.1.

There are many places in our code that define < 4 component images or buffers, and use subscript operator to access/write the values (translating to OpImageFetch or store).

A very common case if reading from depth (float):
```
Texture2D<float>  g_depth : register(t1, space0);
...
int2 pixelPos;
float depth = g_depth[pixelPos];
```
or from x/y velocity (float2):
```
RWTexture2D<float2> g_output : register(u0, space0);
g_output[pixelPos] = float2(blah1, blah2);
```

Compilation succeeds, but runtime validation fails with:
```
SPIR-V module not valid: Expected Result Type to be int or float vector type: ImageFetch
```

The current workaround in a bunch of trivial cases (but very far from ideal) is to make everything a float4, and then use appropriate swizzle masks:
```
Texture2D<float4>  g_depth : register(t1, space0);
...
int2 pixelPos;
float depth = g_depth[pixelPos].x;
```
```
RWTexture2D<float4> g_output : register(u0, space0);
g_output[pixelPos] = float4(blah1, blah2, 0, 0);
```

More complex cases are unable to compile.
Before:
```
RWTexture3D<uint> g_cellSizeTexture : register(u0, space0);
...
InterlockedAdd(g_cellSizeTexture[coord], 1);
```
After:
```
RWTexture3D<uint4> g_cellSizeTexture : register(u0, space0);
...
InterlockedAdd(g_cellSizeTexture[coord].x, 1);
```

FXC obviously disallows interlocked add on vector types, so using uint4 as a workaround won't work, and the following error will be returned:
```
error X3681: cs_5_1 only supports interlocked operations on scalar int or uint data
```

The SPIR-V spec for `OpImageFetch` seems awfully restrictive:
```
Result Type must be a vector of four components of floating-point type or integer type. Its components must be the same as Sampled Type of the underlying OpTypeImage (unless that underlying Sampled Type is OpTypeVoid).
```

Spec aside, glslang needs to syntactically support the examples I mentioned, even if some translation to valid SPIR-V needs to happen under the hood.
Effectively, glslang needs to emit something like:
```
%x = OpImageFetch %v4float ...
%y = OpCompositeExtract %float %x 0
```

This is a pretty big issue for us, currently. So getting it fixed soon would be very appreciated.

Thank you very much!
Graham

**Comment by Anteru** [comment] 2018-04-09 13:46
A side question related to this is if the rules should be relaxed, i.e. let `OpImageFetch` return less than 1 component (as well as the other image fetch instructions.)

**Comment by johnkslang** [comment] 2018-04-09 15:33
Note that `OpImageFetch` is in the company of all the sampled-image filtering operations, it just bypasses the filtering step.  These all return a float4/vec4 because that's how the hardware model works for them, and how GLSL specifies it as well. (Not to be confused with OpImageRead, which operates quite differently.) The API explains how the 4 components map to the result. Reducing these to fewer components is done with a subsequent swizzle, which in GLSL is explicitly in the shader source.

For example, I see in glslang test results for `hlsl.texture.subvec4.frag` like this:

```
              ...
              69:    7(fvec4) ImageFetch 62 67 Sample 68
              70:    6(float) CompositeExtract 69 0
              ...
              72:    7(fvec4) ImageFetch 71 67 Sample 68
              74:    6(float) CompositeExtract 72 0
              75:    6(float) CompositeExtract 72 1
              76:   73(fvec2) CompositeConstruct 74 75
              ...
              78:    7(fvec4) ImageFetch 77 67 Sample 68
              80:    6(float) CompositeExtract 78 0
              81:    6(float) CompositeExtract 78 1
              82:    6(float) CompositeExtract 78 2
              83:   79(fvec3) CompositeConstruct 80 81 82
              ...
```

Will try to address more of this later today.

**Comment by johnkslang** [comment] 2018-04-09 15:48
A bit more data. When I use current glslang on your first example:

```
Texture2D<float>  g_depth;
int2 pixelPos;

float4 main() : SV_Target0
{
    float depth = g_depth[pixelPos];
    return depth;
}
```

I get SPIR-V 

```
              26:    7(fvec4) ImageFetch 16 25 Lod 22
              27:    6(float) CompositeExtract 26 0
```

Which gets the vec4 and subsets to a scalar.  So, I am not yet following what the problem is.

**Comment by gwihlidal** [comment] 2018-04-09 18:08
It doesn’t appear that hlsl spirv tests run the hlsl legalizer? Would you mind trying with that on?

The compilation in glslang succeeds but validation fails with:

`Vulkan validation: Object: 0x0 | SPIR-V module not valid: Expected Result Type to be int or float vector type: ImageFetch`

**Comment by gwihlidal** [comment] 2018-04-09 18:09
Also:
`Vulkan validation: Object: 0x0 | SPIR-V module not valid: Expected Result Type to have 4 components: ImageFetch`

This is with glslang from VK SDK 1.70.1 including hlsl legalizer/optimizer

**Comment by gwihlidal** [comment] 2018-04-09 19:45
Here's a full example that repros for me:
```
Texture2D<float3> g_rtTex			: register(t0);
RWTexture2D<float3> g_lightingTex	: register(u0);

struct PassConstants
{
	uint reflectionsOnly;
};
ConstantBuffer<PassConstants> g_pass : register(b0, space0);

[numthreads(8, 8, 1)]
void reflectionMergeCs(uint3 dispatchThreadId : SV_DispatchThreadID)
{
	uint2 uv = dispatchThreadId.xy;
	float3 lighting = g_pass.reflectionsOnly ? float3(0, 0, 0) : g_lightingTex[uv];
	float3 rt = g_rtTex[uv];

	lighting.xyz += rt;

	g_lightingTex[uv] = lighting;
}
```
```
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 4
; Bound: 92
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %reflectionMergeCs "reflectionMergeCs" %dispatchThreadId
               OpExecutionMode %reflectionMergeCs LocalSize 8 8 1
               OpSource HLSL 500
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %reflectionMergeCs "reflectionMergeCs"
               OpName %g_pass "g_pass"
               OpMemberName %g_pass 0 "reflectionsOnly"
               OpName %g_pass_0 "g_pass"
               OpName %g_lightingTex "g_lightingTex"
               OpName %g_rtTex "g_rtTex"
               OpName %dispatchThreadId "dispatchThreadId"
               OpMemberDecorate %g_pass 0 Offset 0
               OpDecorate %g_pass Block
               OpDecorate %g_pass_0 DescriptorSet 0
               OpDecorate %g_pass_0 Binding 0
               OpDecorate %g_lightingTex DescriptorSet 0
               OpDecorate %g_lightingTex Binding 0
               OpDecorate %g_rtTex DescriptorSet 0
               OpDecorate %g_rtTex Binding 0
               OpDecorate %dispatchThreadId BuiltIn GlobalInvocationId
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
     %v2uint = OpTypeVector %uint 2
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
     %g_pass = OpTypeStruct %uint
%_ptr_Uniform_g_pass = OpTypePointer Uniform %g_pass
   %g_pass_0 = OpVariable %_ptr_Uniform_g_pass Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Uniform_uint = OpTypePointer Uniform %uint
       %bool = OpTypeBool
     %uint_0 = OpConstant %uint 0
    %float_0 = OpConstant %float 0
         %37 = OpConstantComposite %v3float %float_0 %float_0 %float_0
         %39 = OpTypeImage %float 2D 0 0 0 2 Rgba32f
%_ptr_UniformConstant_39 = OpTypePointer UniformConstant %39
%g_lightingTex = OpVariable %_ptr_UniformConstant_39 UniformConstant
         %47 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_47 = OpTypePointer UniformConstant %47
    %g_rtTex = OpVariable %_ptr_UniformConstant_47 UniformConstant
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%dispatchThreadId = OpVariable %_ptr_Input_v3uint Input
%reflectionMergeCs = OpFunction %void None %3
          %5 = OpLabel
         %62 = OpLoad %v3uint %dispatchThreadId
         %71 = OpVectorShuffle %v2uint %62 %62 0 1
         %72 = OpAccessChain %_ptr_Uniform_uint %g_pass_0 %int_0
         %73 = OpLoad %uint %72
         %74 = OpINotEqual %bool %73 %uint_0
               OpSelectionMerge %75 None
               OpBranchConditional %74 %76 %77
         %76 = OpLabel
               OpBranch %75
         %77 = OpLabel
         %78 = OpLoad %39 %g_lightingTex
         %80 = OpImageRead %v3float %78 %71
               OpBranch %75
         %75 = OpLabel
         %91 = OpPhi %v3float %37 %76 %80 %77
         %82 = OpLoad %47 %g_rtTex
         %84 = OpImageFetch %v3float %82 %71 Lod %int_0
         %87 = OpFAdd %v3float %91 %84
         %88 = OpLoad %39 %g_lightingTex
               OpImageWrite %88 %71 %87
               OpReturn
               OpFunctionEnd
```

**Comment by gwihlidal** [comment] 2018-04-09 19:46
```
PS D:\DebugOut> .\spirv-val.exe .\CompBug.spv
error: 68: Expected Result Type to have 4 components: ImageFetch
```

**Comment by gwihlidal** [comment] 2018-04-09 19:52
Using the prebuilt glslc.exe in 1.1.70.1 SDK also repros using this hlsl example:
```
glslc.exe -fhlsl-iomap -fhlsl-offsets -g -fentry-point=reflectionMergeCs -fshader-stage=comp -o CompBug.spv -x hlsl CompBug.hlsl
```
```
PS C:\VulkanSDK\1.1.70.1\Bin> .\spirv-val.exe CompBug.spv
error: 68: Expected Result Type to have 4 components: ImageFetch
```

**Comment by gwihlidal** [comment] 2018-04-09 20:12
Interestingly, this repro that works for you does still fail for me:
```
Texture2D<float>  g_depth;
int2 pixelPos;

float4 main() : SV_Target0
{
    float depth = g_depth[pixelPos];
    return depth;
}
```
```
PS C:\VulkanSDK\1.1.70.1\Bin> .\glslc.exe -fhlsl-iomap -fhlsl-offsets -g -fentry-point=main -fshader-stage=frag -o Test1
.spv -x hlsl Test1.hlsl
PS C:\VulkanSDK\1.1.70.1\Bin> .\spirv-val.exe .\Test1.spv
error: 41: Expected Result Type to be int or float vector type: ImageFetch
```
```
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 4
; Bound: 43
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %_entryPointOutput
               OpExecutionMode %main OriginUpperLeft
               OpSource HLSL 500
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
               OpName %g_depth "g_depth"
               OpName %_Global "$Global"
               OpMemberName %_Global 0 "pixelPos"
               OpName %_ ""
               OpName %_entryPointOutput "@entryPointOutput"
               OpDecorate %g_depth DescriptorSet 0
               OpMemberDecorate %_Global 0 Offset 0
               OpDecorate %_Global Block
               OpDecorate %_ DescriptorSet 0
               OpDecorate %_entryPointOutput Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
         %13 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_13 = OpTypePointer UniformConstant %13
    %g_depth = OpVariable %_ptr_UniformConstant_13 UniformConstant
        %int = OpTypeInt 32 1
      %v2int = OpTypeVector %int 2
    %_Global = OpTypeStruct %v2int
%_ptr_Uniform__Global = OpTypePointer Uniform %_Global
          %_ = OpVariable %_ptr_Uniform__Global Uniform
      %int_0 = OpConstant %int 0
%_ptr_Uniform_v2int = OpTypePointer Uniform %v2int
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
         %37 = OpLoad %13 %g_depth
         %38 = OpAccessChain %_ptr_Uniform_v2int %_ %int_0
         %39 = OpLoad %v2int %38
         %40 = OpImageFetch %float %37 %39 Lod %int_0
         %42 = OpCompositeConstruct %v4float %40 %40 %40 %40
               OpStore %_entryPointOutput %42
               OpReturn
               OpFunctionEnd
```

**Comment by gwihlidal** [comment] 2018-04-09 20:27
More info:
Running the basic depth test shader through glslangValidator.exe (not glslc.exe) produces spirv that passes the validator.
```
glslangValidator.exe --hlsl-iomap --hlsl-offsets -D -g -e main -S frag -V -o Test1_2.spv
```
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 4
; Bound: 46
; Schema: 0
               OpCapability Shader
          %2 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %_entryPointOutput
               OpExecutionMode %main OriginUpperLeft
          %1 = OpString "Test1.hlsl"
               OpSource HLSL 500 %1 "// OpModuleProcessed entry-point main
// OpModuleProcessed hlsl-iomap
// OpModuleProcessed client vulkan100
// OpModuleProcessed target-env vulkan1.0
// OpModuleProcessed hlsl-offsets
#line 1
Texture2D<float>  g_depth;
int2 pixelPos;

float4 main() : SV_Target0
{
    float depth = g_depth[pixelPos];
    return depth;
}"
               OpName %main "main"
               OpName %g_depth "g_depth"
               OpName %_Global "$Global"
               OpMemberName %_Global 0 "pixelPos"
               OpName %_ ""
               OpName %_entryPointOutput "@entryPointOutput"
               OpDecorate %g_depth DescriptorSet 0
               OpMemberDecorate %_Global 0 Offset 0
               OpDecorate %_Global Block
               OpDecorate %_ DescriptorSet 0
               OpDecorate %_entryPointOutput Location 0
       %void = OpTypeVoid
          %4 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
         %14 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_14 = OpTypePointer UniformConstant %14
    %g_depth = OpVariable %_ptr_UniformConstant_14 UniformConstant
        %int = OpTypeInt 32 1
      %v2int = OpTypeVector %int 2
    %_Global = OpTypeStruct %v2int
%_ptr_Uniform__Global = OpTypePointer Uniform %_Global
          %_ = OpVariable %_ptr_Uniform__Global Uniform
      %int_0 = OpConstant %int 0
%_ptr_Uniform_v2int = OpTypePointer Uniform %v2int
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %4
          %6 = OpLabel
               OpLine %1 6 0
         %39 = OpLoad %14 %g_depth
         %40 = OpAccessChain %_ptr_Uniform_v2int %_ %int_0
         %41 = OpLoad %v2int %40
         %42 = OpImageFetch %v4float %39 %41 Lod %int_0
         %43 = OpCompositeExtract %float %42 0
         %45 = OpCompositeConstruct %v4float %43 %43 %43 %43
               OpStore %_entryPointOutput %45
               OpReturn
               OpFunctionEnd
```

**Comment by johnkslang** [comment] 2018-04-09 21:01
I wonder if there is a bad transform getting invoked by shaderc, which is not invoked by glslang? @dneto0 or @antiagainst ?

**Comment by antiagainst** [comment] 2018-04-10 14:31
I tried the example in https://github.com/KhronosGroup/glslang/issues/1340#issuecomment-379871323 with the latest Shaderc, `OpImageFetch` is returning a 4-component vector and spirv-val is happy.

**Comment by antiagainst** [comment] 2018-04-10 14:32
Likely an issue that was in 1.1.70.1 SDK's snapshot of the toolchain that gets fixed now?

**Comment by johnkslang** [comment] 2018-04-10 20:15
Thanks @antiagainst. Yes, would be good to know. Would like to continue figuring it out in SPIRV-Tools https://github.com/KhronosGroup/SPIRV-Tools/issues/1465.

**Comment by greg-lunarg** [comment] 2018-04-12 00:32
FWIW, it seems the glslang commit that fixes this problem went in fairly recently and the shaderc in the 1.1 SDK was not correctly versioned to pick it up. I will go over our process for versioning and building shaderc so that it is correct in the next and future SDKs.

**Comment by johnkslang** [comment] 2018-04-12 00:45
Okay, thanks. It seems we've figured this out now, so I will close.

**Closed by johnkslang** 2018-04-12 00:45 UTC
Labels: question
