### ISSUE TITLE
HLSL: f32tof16 (sometimes) producing constant 0

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1798] opened 2019-06-13 15:19 UTC
When compiling this shader:

```
Buffer<uint> ib;
RWBuffer<uint> ob;

[numthreads(1,1,1)]
void CSMain(uint3 did: SV_DispatchThreadID)
{
    uint a = ib[did.x];
    min16float b = min16float(f16tof32(a));
    b *= b;
    uint c = f32tof16(b);
    ob[did.x] = c;
}
```

With the following options:

```
glslangValidator.exe foo.hlsl -V -e CSMain --hlsl-enable-16bit-types -S comp -D -Od
```

I'm getting the following SPIRV output:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 54
; Schema: 0
               OpCapability Shader
               OpCapability Float16
               OpCapability SampledBuffer
               OpCapability ImageBuffer
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %CSMain "CSMain" %did_1
               OpExecutionMode %CSMain LocalSize 1 1 1
               OpSource HLSL 500
               OpName %CSMain "CSMain"
               OpName %_CSMain_vu3_ "@CSMain(vu3;"
               OpName %did "did"
               OpName %a "a"
               OpName %ib "ib"
               OpName %b "b"
               OpName %c "c"
               OpName %ob "ob"
               OpName %did_0 "did"
               OpName %did_1 "did"
               OpName %param "param"
               OpDecorate %ib DescriptorSet 0
               OpDecorate %ib Binding 0
               OpDecorate %b RelaxedPrecision
               OpDecorate %30 RelaxedPrecision
               OpDecorate %33 RelaxedPrecision
               OpDecorate %34 RelaxedPrecision
               OpDecorate %35 RelaxedPrecision
               OpDecorate %36 RelaxedPrecision
               OpDecorate %37 RelaxedPrecision
               OpDecorate %38 RelaxedPrecision
               OpDecorate %ob DescriptorSet 0
               OpDecorate %ob Binding 0
               OpDecorate %did_1 BuiltIn GlobalInvocationId
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Function_v3uint = OpTypePointer Function %v3uint
          %9 = OpTypeFunction %void %_ptr_Function_v3uint
%_ptr_Function_uint = OpTypePointer Function %uint
         %15 = OpTypeImage %uint Buffer 0 0 0 1 R32ui
%_ptr_UniformConstant_15 = OpTypePointer UniformConstant %15
         %ib = OpVariable %_ptr_UniformConstant_15 UniformConstant
     %uint_0 = OpConstant %uint 0
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
     %v4uint = OpTypeVector %uint 4
       %half = OpTypeFloat 16
%_ptr_Function_half = OpTypePointer Function %half
      %float = OpTypeFloat 32
    %v2float = OpTypeVector %float 2
         %40 = OpTypeImage %uint Buffer 0 0 0 2 R32ui
%_ptr_UniformConstant_40 = OpTypePointer UniformConstant %40
         %ob = OpVariable %_ptr_UniformConstant_40 UniformConstant
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
      %did_1 = OpVariable %_ptr_Input_v3uint Input
     %CSMain = OpFunction %void None %3
          %5 = OpLabel
      %did_0 = OpVariable %_ptr_Function_v3uint Function
      %param = OpVariable %_ptr_Function_v3uint Function
         %50 = OpLoad %v3uint %did_1
               OpStore %did_0 %50
         %52 = OpLoad %v3uint %did_0
               OpStore %param %52
         %53 = OpFunctionCall %void %_CSMain_vu3_ %param
               OpReturn
               OpFunctionEnd
%_CSMain_vu3_ = OpFunction %void None %9
        %did = OpFunctionParameter %_ptr_Function_v3uint
         %12 = OpLabel
          %a = OpVariable %_ptr_Function_uint Function
          %b = OpVariable %_ptr_Function_half Function
          %c = OpVariable %_ptr_Function_uint Function
         %18 = OpLoad %15 %ib
         %20 = OpAccessChain %_ptr_Function_uint %did %uint_0
         %21 = OpLoad %uint %20
         %25 = OpImageFetch %v4uint %18 %21
         %26 = OpCompositeExtract %uint %25 0
               OpStore %a %26
         %30 = OpLoad %uint %a
         %33 = OpExtInst %v2float %1 UnpackHalf2x16 %30
         %34 = OpCompositeExtract %float %33 0
         %35 = OpFConvert %half %34
               OpStore %b %35
         %36 = OpLoad %half %b
         %37 = OpLoad %half %b
         %38 = OpFMul %half %37 %36
               OpStore %b %38
               OpStore %c %uint_0
         %43 = OpLoad %40 %ob
         %44 = OpAccessChain %_ptr_Function_uint %did %uint_0
         %45 = OpLoad %uint %44
         %46 = OpLoad %uint %c
               OpImageWrite %43 %45 %46
               OpReturn
               OpFunctionEnd
```

Note that at the very end, we have

```
               OpStore %c %uint_0
```

So f32tof16 when directly applied to a min16float variable, produces 0. After running optimization passes, the entire chain of computations collapses and the shader writes 0 to output buffer.

This can be worked around by casting f32tof16 argument to float explicitly.

**Comment by johnkslang** [comment] 2020-02-18 14:33
Closing this both as a duplicate of #2070 and also this particular case now working correctly.

**Closed by johnkslang** 2020-02-18 14:33 UTC
