### ISSUE TITLE
gsland new patch break and causing bug 

### ISSUE THREAD

**Issue by xalteropsx** [KhronosGroup/glslang#3664] opened 2024-07-19 03:38 UTC
[ 36%] Preprocessing shader source erf.comp
[ 36%] Preprocessing shader source erf_pack4.comp
[ 36%] Preprocessing shader source erf_pack8.comp
[ 36%] Preprocessing shader source celu.comp
[ 36%] Preprocessing shader source celu_pack4.comp
[ 37%] Preprocessing shader source celu_pack8.comp
[ 37%] Preprocessing shader source convert_ycbcr.comp
[ 38%] Preprocessing shader source vulkan_activation.comp
[ 38%] Built target ncnn-generate-spirv
CMakeFiles\Makefile2:502: recipe for target 'glslang/SPIRV/CMakeFiles/SPIRV.dir/all' failed
mingw32-make.exe[1]: *** [glslang/SPIRV/CMakeFiles/SPIRV.dir/all] Error 2
Makefile:134: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by arcady-lunarg** [comment] 2024-07-19 15:00
Could you provide a bit more detail? Could you try to show what error message is being produced by glslang here, and maybe attach the file that is causing the error as well as the glslang command that is being run?

**Comment by arcady-lunarg** [comment] 2024-09-02 19:54
Having gotten no further info, I have no way to investigate the cause of this issue nor fix it. Closing.

**Closed by arcady-lunarg** 2024-09-02 19:54 UTC
