### ISSUE TITLE
The WASM compilation instruction does not work.

### ISSUE THREAD

**Issue by wdanilo** [KhronosGroup/glslang#3097] opened 2022-12-19 00:04 UTC
I've seen a similar issue here: https://github.com/KhronosGroup/glslang/issues/1950, but it looks like nowadays it fails even earlier than in that instruction.

What I've done so far:

```
$ cd /Users/wdanilo/Dev/emsdk/

Setting up EMSDK environment (suppress these messages with EMSDK_QUIET=1)
Adding directories to PATH:
PATH += /Users/wdanilo/Dev/emsdk
PATH += /Users/wdanilo/Dev/emsdk/upstream/emscripten
PATH += /Users/wdanilo/Dev/emsdk/node/14.18.2_64bit/bin

Setting environment variables:
PATH = /Users/wdanilo/Dev/emsdk:/Users/wdanilo/Dev/emsdk/upstream/emscripten:/Users/wdanilo/Dev/emsdk/node/14.18.2_64bit/bin:/Users/wdanilo/.nvm/versions/node/v16.16.0/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wdanilo/.cargo/bin:/Users/wdanilo/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/wdanilo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/wdanilo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/Users/wdanilo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/Users/wdanilo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/Users/wdanilo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/wdanilo/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/wdanilo/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/wdanilo/.antigen/bundles/romkatv/powerlevel10k
EMSDK = /Users/wdanilo/Dev/emsdk
EMSDK_NODE = /Users/wdanilo/Dev/emsdk/node/14.18.2_64bit/bin/node
EMSDK_PYTHON = /Users/wdanilo/Dev/emsdk/python/3.9.2_64bit/bin/python3
SSL_CERT_FILE = /Users/wdanilo/Dev/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/certifi/cacert.pem

$ cd /Users/wdanilo/Dev/glslang/dist
$ emcmake cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_GLSLANG_JS=ON -DENABLE_HLSL=OFF -DBUILD_TESTING=OFF -DENABLE_OPT=OFF -DINSTALL_GTEST=OFF /Users/wdanilo/Dev/glslang/src
```

The result (error):

```
configure: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_GLSLANG_JS=ON -DENABLE_HLSL=OFF -DBUILD_TESTING=OFF -DENABLE_OPT=OFF -DINSTALL_GTEST=OFF /Users/wdanilo/Dev/glslang/src -DCMAKE_TOOLCHAIN_FILE=/Users/wdanilo/Dev/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/wdanilo/Dev/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
-- Configuring done
CMake Error: Cannot determine link language for target "glslang.js_1_glslang_pre_js".
CMake Error: CMake can not determine linker language for target: glslang.js_1_glslang_pre_js
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
emcmake: error: 'cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_GLSLANG_JS=ON -DENABLE_HLSL=OFF -DBUILD_TESTING=OFF -DENABLE_OPT=OFF -DINSTALL_GTEST=OFF /Users/wdanilo/Dev/glslang/src -DCMAKE_TOOLCHAIN_FILE=/Users/wdanilo/Dev/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/wdanilo/Dev/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads' failed (returned 1)
```

**Comment by wdanilo** [comment] 2022-12-19 00:11
@johnkslang as you helped with the other issue, would you be so nice and take a look at this as well? :)

**Comment by wdanilo** [comment] 2022-12-19 14:14
@greg-lunarg I thought I would mention you too here, as it looks like you are an active contributor to this codebase and this issue is a pretty big blocker for us right now :(

**Comment by jeremy-lunarg** [comment] 2022-12-19 19:54
This is a duplicate of #3088.  Can you try my [PR](https://github.com/KhronosGroup/glslang/pull/3098)?

**Comment by jeremy-lunarg** [comment] 2022-12-20 16:36
This should be fixed by https://github.com/KhronosGroup/glslang/pull/3098. Please reopen if you still see an issue.

**Closed by jeremy-lunarg** 2022-12-20 16:36 UTC
