### ISSUE TITLE
Unreachable code after return inside SPIRV/GlslangToSpv.cpp

### ISSUE THREAD

**Issue by qarmin** [KhronosGroup/glslang#2477] opened 2020-12-07 15:17 UTC
Strange that after case is return, and after that is later a code

https://github.com/KhronosGroup/glslang/blob/e11a2c8bece3dffc2fa6bfd1669b23c6f913ff07/SPIRV/GlslangToSpv.cpp#L3675-L3684

**Comment by johnkslang** [comment] 2020-12-08 20:14
@Tobski could you have a look?  It's a good illusion, but needs a fix.

**Comment by arcady-lunarg** [comment] 2023-01-23 22:14
Duplicate of #2763 which has already been fixed.

**Closed by arcady-lunarg** 2023-01-23 22:14 UTC
Labels: bug, SPIR-V
