### ISSUE TITLE
Stricter criteria for setting ClipDistance capability in SPIR-V?

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#240] opened 2016-04-14 19:51 UTC
Based on current GLSL spec, for versions that support gl_PerVertex, gl_ClipDistance is declared implicitly when the programmer does not redeclare gl_PerVertex without it. For such shaders, this is apparently causing the ClipDistance capability to be set in SPIR-V. This in turn is causing the SPIR-V validation layer to give an error when the API has not enabled ClipDistance in the presence of such shaders. We have had two different complaints against this layer so far for this reason and will likely get more, essentially saying "Why is the layer complaining that I need ClipDistance enabled when I have not explicitly used it?". We have basically responded suggesting that they redeclare gl_PerVertex, but we are wondering if we want to be a little more proactive here.

Do we want to perhaps change glslang to only set the ClipDistance capability when it is actually referenced by the shader?

**Comment by johnkslang** [comment] 2016-04-14 21:59
> Do we want to perhaps change glslang to only set the ClipDistance capability when it is actually referenced by the shader?

Yes, we want to do that.  This is a duplicate of something, but I can't find it right now.

**Comment by johnkslang** [comment] 2016-05-17 01:49
This is now "fixed" by ebb505355d59f61dfc9547f81e14b2d9cd1eb2f0.

Technically, glslang was right. The shaders should be declaring their I/O, if they don't want the default declaration.  GLSL/KHR_vulkan_glsl says if you leave this out, you get the default:

in/out gl_PerVertex {
   gl_Position
   gl_PointSize
   gl_ClipDistance
   gl_CullDistance
}

So, it's really the shaders that are asking for it. But, due to popular demand, I changed glslang to not emit the capabilities for these last two now unless a structure reference actually selects these members.

**Closed by johnkslang** 2016-05-17 01:49 UTC
Labels: bug, SPIR-V
