### ISSUE TITLE
Failure of interpolateAt* with complex swizzle interpolant

### ISSUE THREAD

**Issue by iostrowsINTEL** [KhronosGroup/glslang#411] opened 2016-07-25 12:21 UTC
Using one of the interpolateAt* functions with complex swizzled interpolant cause glslang failure:

<pre>
Id Builder::accessChainGetLValue()
{
    assert(accessChain.isRValue == false);

    transferAccessChainSwizzle(true);
    Id lvalue = collapseAccessChain(); <b>// Handles only individual swizzle</b>

    // If swizzle exists, it is out-of-order or not full, we must load the target vector,
    // extract and insert elements to perform writeMask and/or swizzle.  This does not
    // go with getting a direct l-value pointer.
    assert(accessChain.swizzle.size() == 0); <b>// accessChain.swizzle.size() > 0</b>
    assert(accessChain.component == NoResult);

    return lvalue;
}
</pre>
**Example shader:**
<pre>
#version 440
layout(location = 0) in highp vec4 texCoord;
...
results.floatVal = interpolateAtCentroid(texCoord.x); <b>// OK</b>
results.vec2Val = interpolateAtCentroid(texCoord.xy); <b>// Fail</b>
results.vec3Val = interpolateAtCentroid(texCoord.xyz); <b>// Fail</b>
</pre>

**Comment by johnkslang** [comment] 2016-07-25 15:27
This is a duplicate of issue #290.  Moving its relevant content here, and closing that one.

That is, Khronos decided what this really means as per the following:

For GLSL -> SPIR-V generation: 

```
interpolateAt(a.zx) 
    -> 
    interpolateAt(a).zw
```

and not:

```
interpolateAt(a.zx) 
    ->  
    interpolateAt(a.x)
    interpolateAt(a.z)
```

**Comment by johnkslang** [comment] 2016-07-26 18:56
Addressed by  https://github.com/KhronosGroup/glslang/commit/8c8505c60454549181d78301933f3f108e2f55e6.

This was non-trivial. See if it does everything you believe is needed; reopen if there is still an issue.

**Closed by johnkslang** 2016-07-26 18:56 UTC
Labels: Missing Functionality, SPIR-V

**Comment by iostrowsINTEL** [comment] 2016-07-27 15:29
Works fine, thanks!
