### ISSUE TITLE
Detecting "flattened array with initializer list unsupported" error on valid HLSL code

### ISSUE THREAD

**Issue by bkaradzic** [KhronosGroup/glslang#933] opened 2017-06-11 04:47 UTC
I'm getting "flattened array with initializer list unsupported" here:
https://github.com/KhronosGroup/glslang/blob/f6deacd5790e804ab9817111673b1edd87876bf7/hlsl/hlslParseHelper.cpp#L6978

Triggered on this code:
```cpp
struct BgfxSampler2D
{
	SamplerState m_sampler;
	Texture2D m_texture;
};

uniform SamplerState s_texNormalSampler : register(s1);
uniform Texture2D s_texNormalTexture : register(t1);
static BgfxSampler2D s_texNormal = { s_texNormalSampler, s_texNormalTexture };
```
Microsoft's D3DCompiler is accepting this code.

**Comment by chaoticbob** [comment] 2017-06-13 06:02
There may be some relationship between this and #850.

**Comment by bkaradzic** [comment] 2017-06-13 06:41
@chaoticbob Yeah it looks identical. I was searching for error message and couldn't find it.

**Comment by johnkslang** [comment] 2017-07-16 10:44
Closing this as a duplicate of #980.

**Closed by johnkslang** 2017-07-16 10:44 UTC
Labels: duplicate, HLSL, Missing Functionality
