### ISSUE TITLE
textureProj() with non-vec4 coordinates

### ISSUE THREAD

**Issue by iostrowsINTEL** [KhronosGroup/glslang#319] opened 2016-06-01 15:35 UTC
Glsl textureProj() function with smaller than 4 components vector of texture coordinates is incorrectly translated into SpirV.

SpirV spec for OpImageSampleProjExplicitLod says:
`
Coordinate is a floating-point vector of four components containing (u [, v] [, w], q), as needed by the definition of Sampled Image, with the q component consumed for the projective division. That is, the actual sample coordinate will be (u/q [, v/q] [, w/q]), as needed by the definition of Sampled Image. It may be a vector larger than needed, but all unused components will appear after all used components.
`

So OpImageSampleProjExplicitLod coordinate vector should be transformed into 4 component vector by adding 0 in missing components.

Shader from dEQP-VK.glsl.texture_functions.textureproj.sampler2d_vec3_fixed_vertex (currently in IHV review):

**GLSL:**
```
layout(location = 4) in highp vec3 a_in0;
…
v_color = vec4(textureProj(u_sampler, a_in0))*u_scale + u_bias;
```

**SpirV:**
```
%6 = OpTypeFloat 32
…
%24 = OpTypeVector %6 3
%25 = OpTypePointer Input %24
%26 = OpVariable %25 Input
…
%27 = OpLoad %24 %26
%29 = OpImageSampleProjExplicitLod %7 %23 %27 Lod %28

```

**Comment by johnkslang** [comment] 2016-06-02 00:48
Is `u_sampler` a `sampler2D`? If so, isn't `a_in0` a vector of `(u, v, q)`?  That is what you get by removing the `[, w]` from the spec, so seems legal.

**Comment by iostrowsINTEL** [comment] 2016-06-03 13:34
Yes, it is `sampler2D`. I agree that it should proceed like that, but in this case spec language that `Coordinate is a floating-point vector of`**`four`**`components` must be changed since it is not true.

**Comment by johnkslang** [comment] 2016-06-03 16:41
> coordinate is a floating-point vector of four components

Agreed that should change; four components are allowed but not required.  Does that solve this problem?  If so, this needs to move to https://github.com/KhronosGroup/SPIRV-Headers/issues for the specification change request.

**Comment by johnkslang** [comment] 2016-06-03 17:13
Since the specification problem is real, regardless of this, I submitted the specification issue.

Is there anything else pending here, or can we close?

**Comment by iostrowsINTEL** [comment] 2016-06-06 15:50
That's all, thanks!

**Comment by ChrisGautier** [comment] 2016-06-15 10:44
I think the problem is not fully addressed. There was a small SPIR-V spec inconsistency (now resolved), but there is still a glslangValidator issue.

In ESSL, textureProj on a sampler2D can be provided via either a vec3 or a vec4. From the ESSL specs:

==== 

`gvec4 textureProj (gsampler2D sampler, vec3 P [, float bias] )`
`gvec4 textureProj (gsampler2D sampler, vec4 P [, float bias] )`

The third component of P is ignored when sampler has type gsampler2D and P has type vec4.

==== 


But from the SPIR-V perspective, in both cases, the w coordinate remains in the third position, since "all unused components will appear after all used components". That means glslangValidator should compact the ESSL vec4 'P' parameter into a vec3, by deleting the unused third parameter.

**Comment by scyganINTEL** [comment] 2016-06-16 12:26
@ChrisGautier  since I and @iostrowsINTEL  stumbled upon same issue (and since there is sadly no 'reopen' button): I  have filed that as #343, hope you don't mind,

**Comment by ChrisGautier** [comment] 2016-06-16 12:40
> hope you don't mind

Not at all, I was considering creating one myself since, as you said, it was not possible to reopen the issue. Thanks :)

**Comment by johnkslang** [comment] 2016-06-16 16:15
Looks like someone can request reopen, and I can reopen.

**Comment by johnkslang** [comment] 2016-06-16 16:18
Closing again, as this is now captured in #343.

**Closed** 2016-06-17 08:26 UTC
Labels: Specification
