### ISSUE TITLE
GLSL shaders using GL_AMD_gpu_shader_half_float should not generate "OpCapability Float16"..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/glslang#1273] opened 2018-03-06 07:52 UTC
Hi @amdrexu,
just testing SPIR-V code using Float16 Cap+SPV_AMD_gpu_shader_half_float  generated from HLSL min16float using DXC seems uncovered issues with both SPIRV-Tools spirv-opt (https://github.com/KhronosGroup/SPIRV-Tools/issues/1376) and spirv-val (https://github.com/KhronosGroup/SPIRV-Tools/issues/1375)
and the accepted solution seems to be to disable SPIR-V Float16 cap on this cases (https://github.com/Microsoft/DirectXShaderCompiler/pull/1109):
please see extract from here: https://github.com/Microsoft/DirectXShaderCompiler/issues/1095

> Capability Float16 is not allowed by Vulkan 1.0 specification.
> SPV_AMD_gpu_shader_half_float should be used if 16bit floats are used.

> Upon further discussion, it seems that we should not emit OpCapability Float16, and should only emit the extension. The drivers that support this extension should work once they see the extension in the SPIR-V binary even in the absence of the capability.
> 
> SPV_AMD_gpu_shader_half_float does not enable SPIR-V's Float16 capability.

so just asking if you can fix glslang also as is clearly emitting Float16 also..
sad thing is that with SPIRV-Tools from Vulkan SDK 1.0.68 I don't have any issues validating the resulting SPIR-V file but using current master branch I would see issues as DXC SPIR-V devs pointed..

I attach repro shaders: 
[reproglslfloat16.zip](https://github.com/KhronosGroup/glslang/files/1783970/reproglslfloat16.zip)
I'm using shaderfp16.comp with f16vec2 usage and glslang generates SPIR-V file with :

>                OpCapability Float16
>                OpExtension "SPV_AMD_gpu_shader_half_float"
which seems is not ok per previous discussion..
The repro files are generated as follows from glslang +SPIRV-Tools from VUlkan sdk 1.0.68:
```
glslangValidator  --target-env vulkan1.0 -e main -S  comp -DWIDTH=1920 -DHEIGHT=1080 -DWORKGROUP_SIZE=32 shaderfp16.comp -o shaderfp16.comp.spv
spirv-dis "shaderfp16.comp.spv" -o "shaderfp16.comp.spv.dis"
spirv-val shaderfp16.comp.spv
spirv-opt shaderfp16.comp.spv -o out.spv
```

**Comment by amdrexu** [comment] 2018-03-06 08:14
Usually, when the SPV extension is developed. It often introduces both the SPV extension string in OpExtension and a new capability in OpCapability. For SPV_AMD_gpu_shader_half_float, we have native capability defined in SPIR-V spec. So we do not invent a new capability like Float16AMD (rather, we introduce Float16ImageAMD). We borrow the existing capability. I think both the extension string and the capability should be emitted  in the SPIR-V binary to highlight the use of float16. In other SPV extensions like SPV_KHR_shader_ballot, both extension string and the capability are generated. I understand the dilemma SPIRV-tools has encountered. Because SPV_KHR_16bit_storage is not a part of Vulkan 1.0, it disallows the use of float16 in SPIR-V binary. But as far as I am concerned, I think once the extension string is specified, we should loosen the validation rule.

**Comment by oscarbg** [comment] 2018-03-06 08:21
yeah.. 
really don't matter the exact solution to me, as long as all DXC+SPIRV-Tools+glslangValidator operate correctly, and AMD driver is happy with the SPIR-V provided by both DXC and SPIRV-Tools+glslangValidator..
so can you answer me if AMD Vulkan driver is happy with SPIR-V shaders using SPV_AMD_gpu_shader_half_float but **without OpCapability Float16**?

**Comment by oscarbg** [comment] 2018-03-06 10:38
nice.. thanks for clarification..
let me ask you a somewhat related question..
I'm pretty sure I have found what appears to be a bug on D3D driver on RX Vega regarding min16float (i.e. using float16 on HLSL).. note AMD D3D driver advertices min16float support as optinal capability altough program doesn't check for it.. include a minimal mandelbrot executable using min16float shader that renders correctly on Intel HD 530 using min16float (and even provides >60% speedup vs float and also reduced precision is easily shown vs float as you zoom in with left mouse button)..
I attach repro:
[repro.zip](https://github.com/KhronosGroup/glslang/files/1784584/repro.zip)

 and would be glad if you can forward (or at least point to me how to this bug get noticed ) to your AMD D3D colleagues to give it a shot..
you seem to work at AMD Vulkan team but as you have AMD Vega for sure to test you can see I'm correct in that renders bad.. 
from repro:
> launch mandel.exe program should show in menu bar scalar floats but is using min16float computations..
> it's using CSMandelJulia_scalarFloat kernel compiled at runtime from mandel.hlsl file..
> you can check minimal modifications done to this kernel for adding min16float support on it vs original float precision on mandelori.hlsl file
> Notes:
> 1) I'm getting severe graphical issues on RX Vega latest drivers and original float kernel renders correctly on RX Vega..
> 2)no errors/warning shown with D3D debug layers..
> 3)no errors return when compiling shader from  D3DCompileFromFile function 
> 4)renders OK with Intel HD 530 GPU supporting min16float providing more than 50% speedup vs float computation and zooming in shows its calculating in 16bit float precision as not much zoom vs float..

**Comment by amdrexu** [comment] 2018-03-06 13:50
It's OK. I will file an internal ticket to D3D driver team. Which DX version you are using, DX12 or DX11?

**Comment by oscarbg** [comment] 2018-03-06 14:30
Thanks.. It’s using D3D11..

**Comment by dneto0** [comment] 2018-03-06 22:15
>  But as far as I am concerned, I think once the extension string is specified, we should loosen the validation rule. 

Yes, we are relaxing the SPIRV-Tools validator like that.  See
https://github.com/KhronosGroup/SPIRV-Tools/pull/1381

**Comment by amdrexu** [comment] 2018-03-06 22:30
Thanks for your quick fix.

**Comment by oscarbg** [comment] 2018-03-23 16:17
@amdrexu sorry in advance, I know this is not correct way/place to ask but do you know something about the D3D11 repro exhibiting a possible min16float on Vega HW I sent you two weeks ago here.. would be nice at least if they had time to reproduce locally/and they are interested to fix/already fixed on internal driver code and the like..
thanks..

**Comment by amdrexu** [comment] 2018-03-25 23:34
The issue is reported and is assigned to D3D team for investigation. It seems they have reproduced it and is further looking into it from the issue log.

**Comment by oscarbg** [comment] 2018-03-26 09:06
Thanks for the update!

**Comment by arcady-lunarg** [comment] 2023-06-01 21:10
Sounds like the original issue here was resolved by a fix to spirv-val.

**Closed by arcady-lunarg** 2023-06-01 21:10 UTC
Labels: question, SPIR-V, HLSL
