### ISSUE TITLE
Entry point loses correct return type [was: Can't get simple shader to compile properly]

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#487] opened 2016-08-26 17:52 UTC
I'm trying to compile a very simple hlsl shader to spir-v to test and compare vs glsl. I can't get it to generate valid spir-v though.

`float4 entryPoint() : SV_TARGET0
{
	return float4(1, 0, 0, 0);
}`

Using this command line 

glslangValidator.exe example.hlsl -D -V -H -S frag -o example.hlsl.spv -e entryPoint

makes it generate the following SPIR-V

```
example.hlsl
Linked fragment stage:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 12
                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "entryPoint"
                              ExecutionMode 4 OriginUpperLeft
                              Name 4  "entryPoint"
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:    6(float) Constant 1065353216
               9:    6(float) Constant 0
              10:    7(fvec4) ConstantComposite 8 9 9 9
   4(entryPoint):           2 Function None 3
               5:             Label
                              ReturnValue 10
                              FunctionEnd
```

I'm seeing that it's declaring entryPoint as a void function, but still returning a float4. If I do the same with this very simple glsl shader,

```
#version 140
out vec4 outColor;
void main()
{
	outColor = vec4(1, 0, 0, 0);
}
```

the output SPIR-V is

```
example.glsl
Linked fragment stage:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 13
                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 140
                              Name 4  "main"
                              Name 9  "outColor"
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
     9(outColor):      8(ptr) Variable Output
              10:    6(float) Constant 1065353216
              11:    6(float) Constant 0
              12:    7(fvec4) ConstantComposite 10 11 11 11
         4(main):           2 Function None 3
               5:             Label
                              Store 9(outColor) 12
                              Return
                              FunctionEnd
```

You can see that it only states Return now, as is correct for opengl. What I assume is correct behavior is to declare an out variable and write to it.

Is this a known bug?

**Comment by johnkslang** [comment] 2016-08-26 18:18
Something is making the declared entry point void (if you misspell it, it gets the right type), I think it's a duplicate of #480, but I will fix soon anyway.

**Comment by johnkslang** [comment] 2016-08-28 23:26
As it turns out, this was missing functionality.  In SPIR-V, the graphics entry-point is `void` and has no inputs/outputs (at least by convention), and instead all outputs are variables in the **Output** storage class.  Input parameters were already handled, but not yet outputs or the return value.

Merge request #490 fixes this.  It's a pretty big change, changing 83 HLSL tests.  Will pull it in soon, after getting some feedback about it.  Hopefully, we don't have too many merge conflicts with other work, as it is tedious to verify 83 tests getting different results.

**Comment by redorav** [comment] 2016-08-28 23:50
Sorry I realize right now that I put my comment in bug #480 instead of this one. It's really cool that this has been fixed. I look forward to putting it in action once the request goes through.

**Closed** 2016-08-30 00:16 UTC
Labels: bug, HLSL
