### ISSUE TITLE
SPIRV: Are structurally equivalent `TypeStruct`s equivalent?

### ISSUE THREAD

**Issue by tangent-vector** [KhronosGroup/glslang#988] opened 2017-07-13 19:58 UTC
I am seeing an issue where a released Vulkan driver balks at SPIR-V input generating by glslang, saying, e.g.:

```
Error: SPIR-V module not valid: OpFunctionCall Argument <id> '33's type does not match Function <id> '8's parameter type.
```

In the source GLSL, the function declaration and the argument passed to it both use the same `struct` type, but in the generated SPIR-V, the function argument and the parameter each refer to distinct but (AFAICT) structurally equivalent `OpTypeStruct`s.

I'm attaching a file `test.frag` that shows this behavior, and the file `test.spv.asm` that results from compiling it through our pipeline (which invokes glslang through the library interface).

If structurally-equivalent `OpTypeStruct`s are supposed to be equivalent types, it would seem to mean the driver is in error, but I don't see this spelled out clearly in the SPIR-V spec. If they are not equivalent, then it appears that gslang is producing bad code.

One possible culprit here is that I am directly passing a variable of `struct` type from a `uniform` block in as a function argument. I don't know how common this idiom is.
[test.zip](https://github.com/KhronosGroup/glslang/files/1146497/test.zip)

**Comment by johnkslang** [comment] 2017-07-14 01:41
This is discussed in section 2.8 "Types and Variables":

>Two different type `<id>s` form, by definition, two different types. It is valid to declare multiple aggregate type `<id>s` having the same opcode and operands. This is to allow multiple instances of aggregate types with the same structure to be decorated differently.

Such "aliased" structures are not the same type, and cannot be used interchangeably in SPIR-V, which creates some difficulties, and they are interchangeable in GLSL and HLSL.

There is code in a couple places attempting to get all the member-wise copies right for aliased struct types, and there may be some cases not yet caught. We have at least one open issue for such a case, and internally, a possible SPIR-V mechanism is being considered to allow copies between such types without resorting to member-by-member copies.

**Comment by tfoleyNV** [comment] 2017-07-14 15:20
Thanks for pointing to the spec language. That definitely clarifies that this looks like a glslang bug.

Just in case my attachments to the original message weren't visible,here is the input GLSL:

```
#version 450 core
//TEST:COMPARE_GLSL:

struct Foo
{
	float x;
	float y;
};

float doIt(Foo f)
{
	return f.x + f.y;
}

layout(binding = 0)
uniform U
{
	Foo gFoo;
	
};

layout(location = 0)
out vec4 result;

void main()
{
	result = vec4(doIt(gFoo));
}
```

and here is the output SPIR-V I'm seeing:

```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 43

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 26
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              SourceExtension  "GL_GOOGLE_cpp_style_line_directive"
                              Name 4  "main"
                              Name 7  "Foo"
                              MemberName 7(Foo) 0  "x"
                              MemberName 7(Foo) 1  "y"
                              Name 11  "doIt(struct-Foo-f1-f11;"
                              Name 10  "f"
                              Name 26  "result"
                              Name 27  "Foo"
                              MemberName 27(Foo) 0  "x"
                              MemberName 27(Foo) 1  "y"
                              Name 28  "U"
                              MemberName 28(U) 0  "gFoo"
                              Name 30  ""
                              Name 31  "Foo"
                              MemberName 31(Foo) 0  "x"
                              MemberName 31(Foo) 1  "y"
                              Name 33  "param"
                              Decorate 26(result) Location 0
                              MemberDecorate 27(Foo) 0 Offset 0
                              MemberDecorate 27(Foo) 1 Offset 4
                              MemberDecorate 28(U) 0 Offset 0
                              Decorate 28(U) Block
                              Decorate 30 DescriptorSet 0
                              Decorate 30 Binding 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
          7(Foo):             TypeStruct 6(float) 6(float)
               8:             TypePointer Function 7(Foo)
               9:             TypeFunction 6(float) 8(ptr)
              13:             TypeInt 32 1
              14:     13(int) Constant 0
              15:             TypePointer Function 6(float)
              18:     13(int) Constant 1
              24:             TypeVector 6(float) 4
              25:             TypePointer Output 24(fvec4)
      26(result):     25(ptr) Variable Output
         27(Foo):             TypeStruct 6(float) 6(float)
           28(U):             TypeStruct 27(Foo)
              29:             TypePointer Uniform 28(U)
              30:     29(ptr) Variable Uniform
         31(Foo):             TypeStruct 6(float) 6(float)
              32:             TypePointer Function 31(Foo)
              34:             TypePointer Uniform 27(Foo)
         4(main):           2 Function None 3
               5:             Label
       33(param):     32(ptr) Variable Function
              35:     34(ptr) AccessChain 30 14
              36:     27(Foo) Load 35
              37:    6(float) CompositeExtract 36 0
              38:     15(ptr) AccessChain 33(param) 14
                              Store 38 37
              39:    6(float) CompositeExtract 36 1
              40:     15(ptr) AccessChain 33(param) 18
                              Store 40 39
              41:    6(float) FunctionCall 11(doIt(struct-Foo-f1-f11;) 33(param)
              42:   24(fvec4) CompositeConstruct 41 41 41 41
                              Store 26(result) 42
                              Return
                              FunctionEnd
11(doIt(struct-Foo-f1-f11;):    6(float) Function None 9
           10(f):      8(ptr) FunctionParameter
              12:             Label
              16:     15(ptr) AccessChain 10(f) 14
              17:    6(float) Load 16
              19:     15(ptr) AccessChain 10(f) 18
              20:    6(float) Load 19
              21:    6(float) FAdd 17 20
                              ReturnValue 21
                              FunctionEnd
```

The conflict is that `33(param)`, of type `32: TypePointer Function` to `31(Foo): TypeStruct ...` is being passed as an argument value to the function `11(doIt...` that declares parameter `10(f)` of type `8: TypePointer Function` to `7(Foo): TypeStruct ...`.

Both of these `TypeStruct`s for `Foo` appear to have the same decoration.

There is a third definition of `Foo` in the SPIR-V, `27(Foo)`, (which is textually between the other two, if that matters). This type has distinct decorations, because it also includes, e.g., `MemberDecorate 27(Foo) 0 Offset 0`, etc.

Modifying the body of `main` to move `gFoo` into a temporary before the call:

```
void main()
{
	Foo tmp = gFoo;
	result = vec4(doIt(tmp));
}
```

Seems to work around the issue. There are only two versions of `Foo` in the SPIR-V after that change (instead of three), and the function argument and parameter both use the same type `<id>`.

**Comment by arcady-lunarg** [comment] 2023-06-29 22:53
This no longer reproduces with current versions of glslang. Closing.

**Closed by arcady-lunarg** 2023-06-29 22:53 UTC
Labels: bug, SPIR-V
