### ISSUE TITLE
Compilation in MSYS2/MinGW with GCC 13.1 fails: symbols not declared in this scope (missing cstdint include?)

### ISSUE THREAD

**Issue by LigH-de** [KhronosGroup/glslang#3213] opened 2023-05-07 16:00 UTC
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11415423/logs.zip)

excerpt from compile log:
```
[287/350] Building CXX object glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/glslang_tab.cpp.obj
FAILED: glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/glslang_tab.cpp.obj 
G:\MABS\msys64\mingw32\bin\ccache.exe  g++ -DENABLE_HLSL -DENABLE_OPT=1 -DGLSLANG_OSINCLUDE_WIN32 -IG:/MABS/build/glslang-git/build-32bit/include -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG -std=c++17 -Wall -Wmaybe-uninitialized -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wunused-but-set-parameter -Wunused-but-set-variable -fno-exceptions -Wno-reorder -fno-rtti -Werror=deprecated-copy -MD -MT glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/glslang_tab.cpp.obj -MF glslang\CMakeFiles\MachineIndependent.dir\MachineIndependent\glslang_tab.cpp.obj.d -o glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/glslang_tab.cpp.obj -c G:/MABS/build/glslang-git/glslang/MachineIndependent/glslang_tab.cpp
In file included from MachineIndependent/glslang.y:86:
G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:649:18: error: 'uint32_t' does not name a type
  649 |     static const uint32_t LevelFlagBitOffset = 56;
      |                  ^~~~~~~~
G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:71:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   70 | #include "../Include/InfoSink.h"
  +++ |+#include <cstdint>
   71 | 
G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:662:22: error: 'uint64_t' does not name a type
  662 |     static constexpr uint64_t uniqueIdMask = (1LL << LevelFlagBitOffset) - 1;
      |                      ^~~~~~~~
G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:662:22: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```

Mentioned in [m-ab-s issue 2433](https://github.com/m-ab-s/media-autobuild_suite/issues/2433)

**Comment by Ajaja** [comment] 2023-05-08 08:52
Yes, adding ```#include <stdint.h>``` to ```glslang\Include\Common.h``` solves the problem.

**Comment by diegocr** [comment] 2023-05-08 12:52
Dupe of #3139 (which is been filed since Feb) and for which a PR exists under #3144 (?) 👀

**Comment by LigH-de** [comment] 2023-05-08 21:51
True, I missed the suite updating to GCC 13.

**Comment by LigH-de** [comment] 2023-05-11 20:23
The media-autobuild suite uses glslang indirectly via shaderc; so our progress depends twice on the review of [PR 3144](https://github.com/KhronosGroup/glslang/pull/3144) by @jeremy-lunarg to commit at least the additional include.

**Closed** 2023-07-19 22:23 UTC
