### ISSUE TITLE
Platform dependence on parsing floating-point numbers.

### ISSUE THREAD

**Issue by awefers** [KhronosGroup/glslang#1456] opened 2018-07-25 18:14 UTC
Hi,

I just upgraded to the latest Vulkan SDK for macOS (v1.1.77.0) available on LunarG. I am using HLSL as shading language and noticed that one of my shaders is now broken after switching to the new version of glslangValidator. After some investigation, it turns out that global const variable values are incorrect.

Here is a simple repro case:

HLSL:

	// test.frag.hlsl

	static const float kValue = 0.5f;

	float4 main() : SV_TARGET0
	{
		return float4( kValue );
	}

Compiled via "glslangValidator -Os -V -e main -o test.frag.spv test.frag.hlsl".

Output of "spirv-dis test.frag.spv":

	; SPIR-V
	; Version: 1.0
	; Generator: Khronos Glslang Reference Front End; 7
	; Bound: 17
	; Schema: 0
				   OpCapability Shader
			  %1 = OpExtInstImport "GLSL.std.450"
				   OpMemoryModel Logical GLSL450
				   OpEntryPoint Fragment %main "main" %_entryPointOutput
				   OpExecutionMode %main OriginUpperLeft
				   OpSource HLSL 500
				   OpName %main "main"
				   OpName %_entryPointOutput "@entryPointOutput"
				   OpDecorate %_entryPointOutput Location 0
		   %void = OpTypeVoid
			  %3 = OpTypeFunction %void
		  %float = OpTypeFloat 32
		%v4float = OpTypeVector %float 4
		%float_0 = OpConstant %float 0
			 %12 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
	%_ptr_Output_v4float = OpTypePointer Output %v4float
	%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
		   %main = OpFunction %void None %3
			  %5 = OpLabel
				   OpStore %_entryPointOutput %12
				   OpReturn
				   OpFunctionEnd

Output of "spirv-cross test.frag.spv":

	#version 450

	layout(location = 0) out vec4 _entryPointOutput;

	void main()
	{
		_entryPointOutput = vec4(0.0);
	}

I have seen other places in larger shaders where it would replace the constant values incorrectly with uintBitsToFloat(0x7f800000u) (equivalent of INF). Is this already fixed in mainline?

Thank you,
Axel

**Comment by awefers** [comment] 2018-07-25 20:22
I just checked on Windows with Vulkan SDK v1.1.77.0 and it does not reproduce there.

**Comment by awefers** [comment] 2018-07-25 20:57
The output of "glslangValidator -version" is the same for both SDKs:

Glslang Version: 7.7.2767
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 7.2767
GLSL Version: 4.60 glslang Khronos. 7.2767
SPIR-V Version 0x00010300, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 7
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100

**Comment by johnkslang** [comment] 2018-07-25 21:54
Current master does not do this.  I get 

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %_entryPointOutput
               OpExecutionMode %main OriginUpperLeft
               OpSource HLSL 500
               OpName %main "main"
               OpName %_entryPointOutput "@entryPointOutput"
               OpDecorate %_entryPointOutput Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
  %float_0_5 = OpConstant %float 0.5
         %12 = OpConstantComposite %v4float %float_0_5 %float_0_5 %float_0_5 %float_0_5
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpStore %_entryPointOutput %12
               OpReturn
               OpFunctionEnd
```

Your version seems to be about 66 commits behind master, Jun 5, almost 2 months old.  How old is your SDK?

**Comment by awefers** [comment] 2018-07-25 21:58
That's happening with the latest Vulkan SDK (v1.1.77.0) for macOS that I downloaded yesterday from: https://vulkan.lunarg.com/sdk/home

Direct download link: 
https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.77.0/mac/vulkansdk-macos-1.1.77.0.tar.gz

**Comment by awefers** [comment] 2018-07-25 22:00
So basically something is out of sync with the build machines that generate the downloadable archives for https://vulkan.lunarg.com/sdk/home

It would be great if the macOS download could be fixed.

**Comment by karl-lunarg** [comment] 2018-07-25 23:18
I just repeated this test with the MacOS 1.1.77.0 SDK and got:

```shell
MrMackey:bin karl$ pwd
/Users/karl/Desktop/sdk/vulkansdk-macos-1.1.77.0/macOS/bin
MrMackey:bin karl$ cat test.frag.hlsl 
static const float kValue = 0.5f;

float4 main() : SV_TARGET0
{
	return float4( kValue );
}
MrMackey:bin karl$ ./glslangValidator -Os -V -e main -o test.frag.spv test.frag.hlsl
test.frag.hlsl
MrMackey:bin karl$ ./spirv-dis test.frag.spv 
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 17
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %_entryPointOutput
               OpExecutionMode %main OriginUpperLeft
               OpSource HLSL 500
               OpName %main "main"
               OpName %_entryPointOutput "@entryPointOutput"
               OpDecorate %_entryPointOutput Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
  %float_0_5 = OpConstant %float 0.5
         %12 = OpConstantComposite %v4float %float_0_5 %float_0_5 %float_0_5 %float_0_5
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpStore %_entryPointOutput %12
               OpReturn
               OpFunctionEnd
MrMackey:bin karl$ ./spirv-cross test.frag.spv 
#version 450

layout(location = 0) out vec4 _entryPointOutput;

void main()
{
    _entryPointOutput = vec4(0.5);
}

MrMackey:bin karl$ ./glslangValidator --version
Glslang Version: 7.7.2767
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 7.2767
GLSL Version: 4.60 glslang Khronos. 7.2767
SPIR-V Version 0x00010300, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 7
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
MrMackey:bin karl$ 
```

This looks like the correct results to me.

@awefers Can you check to make sure that you were actually running the `glslangValidator` binary from the SDK and not from someplace else on your system?

**Comment by awefers** [comment] 2018-07-25 23:32
As an additonal test, I did build our full shader set and I am still seeing the problem there. When I look at the shaders from this set I am usually seeing "uintBitsToFloat(0x7f800000u)" instead of the constants when converting back with spirv-cross. This was working fine before I did upgrade to the glslangValidator included with 1.1.77.0 so something is going on.

**Comment by awefers** [comment] 2018-07-25 23:34
I wonder if it is an initialization issue somewhere in glslangValidator.

**Comment by karl-lunarg** [comment] 2018-07-25 23:41
It may be good to double-check that you're using the right modules, given the inconsistent results.

glslang commit 2c8265bb620300047bb9241e39c60c7afe3a81cb was used to build glslang for all three platforms in the SDK 1.1.77.0.  This commit was made on June 11 and the SDK was released on June 20. 

> I wonder if it is an initialization issue somewhere in glslangValidator.

Could be.  That might explain the difference in behavior between platforms.

You might also try building the current glslang master branch to see if you see any improvement.

**Comment by awefers** [comment] 2018-07-25 23:46
I am definitely using the right modules, the shader build system is completely sandboxed, does not even inherit PATH and has an explicit directory with binaries that it can use (basically there is only glslangValidator from the Vulkan SDK). I also verified that the build system uses those binaries (it has a verbose mode).

**Comment by awefers** [comment] 2018-07-26 00:01
Just built glslangValidator from source (from the master branch) with SPIRV-Tools for HLSL legalization and I am still seeing the issue.

**Comment by karl-lunarg** [comment] 2018-07-26 00:07
> I am definitely using the right modules

Good to rule that out.

FWIW, I cannot repro the problem on Linux.   But on Linux, with a Release build of this same commit, I observe a couple compiler warnings:

```shell
/home/karl/src/glslang/StandAlone/StandAlone.cpp: In function ‘void CompileShaders(glslang::TWorklist&)’:
/home/karl/src/glslang/StandAlone/StandAlone.cpp:735:25: warning: ‘workItem’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     glslang::TWorkItem* workItem;


/home/karl/src/glslang/glslang/MachineIndependent/intermOut.cpp: In function ‘void glslang::OutputDouble(TInfoSink&, double, glslang::TOutputTraverser::EExtraOutput)’:
/home/karl/src/glslang/glslang/MachineIndependent/intermOut.cpp:1133:63: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             long long b = *reinterpret_cast<long long*>(&value);

```
I'm not saying this is the problem, but just noting it.

Have you tried a Debug build?

**Comment by awefers** [comment] 2018-07-26 00:34
I only tried the release build (to be as close to the downloadable version as possible). I will try a debug build as well.

**Comment by johnkslang** [comment] 2018-07-26 05:10
Note I addressed one of those build warnings long ago. Not only does it have nothing to do with the current issue, the current issue should be debugged on such an old version of glslang.

**Comment by johnkslang** [comment] 2018-07-26 06:15
> uintBitsToFloat(0x7f800000u) but vec(0.0f).

Glslang does not produce things that look like that. I don't know what you are actually looking at.

If you can send me an example that does reproduce with TOT, I will figure it out. As in HLL and SPIR-V for

HLL -> glslang  -> SPIR-V

where the SPIR-V is an incorrect representation of the HLL.

**Comment by awefers** [comment] 2018-07-26 06:20
As mentioned earlier in the thread, the source is generated with SPIRV-Cross from the SPIRV byte code generated by glslangValidator. The SPIRV byte code is incorrect as well, so it is not a Spirv-Cross issue. I will get you a better example.

**Comment by awefers** [comment] 2018-07-26 17:00
Alright, I did experiment a little more with the simple example from above on **macOS** with glslangValidator built from TOT (master branch).

The original example:

	static const float kValue = 0.5f;

	float4 main() : SV_TARGET0
	{
		return float4( kValue );
	}

Correctly generates the following SPIRV-V (output via spirv-dis):

	; SPIR-V
	; Version: 1.0
	; Generator: Khronos Glslang Reference Front End; 7
	; Bound: 17
	; Schema: 0
	               OpCapability Shader
	          %1 = OpExtInstImport "GLSL.std.450"
	               OpMemoryModel Logical GLSL450
	               OpEntryPoint Fragment %main "main" %_entryPointOutput
	               OpExecutionMode %main OriginUpperLeft
	               OpSource HLSL 500
	               OpName %main "main"
	               OpName %_entryPointOutput "@entryPointOutput"
	               OpDecorate %_entryPointOutput Location 0
	       %void = OpTypeVoid
	          %3 = OpTypeFunction %void
	      %float = OpTypeFloat 32
	    %v4float = OpTypeVector %float 4
	  %float_0_5 = OpConstant %float 0.5
	         %12 = OpConstantComposite %v4float %float_0_5 %float_0_5 %float_0_5 %float_0_5
	%_ptr_Output_v4float = OpTypePointer Output %v4float
	%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
	       %main = OpFunction %void None %3
	          %5 = OpLabel
	               OpStore %_entryPointOutput %12
	               OpReturn
	               OpFunctionEnd

Second test, use PI:

	static const float kValue = 3.141592653589793f;

	float4 main() : SV_TARGET0
	{
		return kValue;
	}

This generates incorrect SPIRV, the constant value evaluates to 0.0:

	; SPIR-V
	; Version: 1.0
	; Generator: Khronos Glslang Reference Front End; 7
	; Bound: 17
	; Schema: 0
	               OpCapability Shader
	          %1 = OpExtInstImport "GLSL.std.450"
	               OpMemoryModel Logical GLSL450
	               OpEntryPoint Fragment %main "main" %_entryPointOutput
	               OpExecutionMode %main OriginUpperLeft
	               OpSource HLSL 500
	               OpName %main "main"
	               OpName %_entryPointOutput "@entryPointOutput"
	               OpDecorate %_entryPointOutput Location 0
	       %void = OpTypeVoid
	          %3 = OpTypeFunction %void
	      %float = OpTypeFloat 32
	    %v4float = OpTypeVector %float 4
	    %float_0 = OpConstant %float 0
	         %12 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
	%_ptr_Output_v4float = OpTypePointer Output %v4float
	%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
	       %main = OpFunction %void None %3
	          %5 = OpLabel
	               OpStore %_entryPointOutput %12
	               OpReturn
	               OpFunctionEnd

Third test, use reciprocal PI:

	static const float kValue = 1.0f / 3.141592653589793f;

	float4 main() : SV_TARGET0
	{
		return kValue;
	}

This generates incorrect SPIRV, the constant value evaluates to 0x1p+128 (what translates with spirv-cross to uintBitsToFloat(0x7f800000u)):

	; SPIR-V
	; Version: 1.0
	; Generator: Khronos Glslang Reference Front End; 7
	; Bound: 17
	; Schema: 0
	               OpCapability Shader
	          %1 = OpExtInstImport "GLSL.std.450"
	               OpMemoryModel Logical GLSL450
	               OpEntryPoint Fragment %main "main" %_entryPointOutput
	               OpExecutionMode %main OriginUpperLeft
	               OpSource HLSL 500
	               OpName %main "main"
	               OpName %_entryPointOutput "@entryPointOutput"
	               OpDecorate %_entryPointOutput Location 0
	       %void = OpTypeVoid
	          %3 = OpTypeFunction %void
	      %float = OpTypeFloat 32
	    %v4float = OpTypeVector %float 4
	%float_0x1p_128 = OpConstant %float 0x1p+128
	         %12 = OpConstantComposite %v4float %float_0x1p_128 %float_0x1p_128 %float_0x1p_128 %float_0x1p_128
	%_ptr_Output_v4float = OpTypePointer Output %v4float
	%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
	       %main = OpFunction %void None %3
	          %5 = OpLabel
	               OpStore %_entryPointOutput %12
	               OpReturn
	               OpFunctionEnd

**Comment by awefers** [comment] 2018-07-26 17:13
Looks like it is related to parsing the decimal number? Assuming 3.141592653589793f evaluates in th e parser to 0.0f (as in the second example), then  0x1p+128 would make sense since it would be produced via ( 1.0f / 0.0f ).

**Comment by awefers** [comment] 2018-07-26 17:24
Alright, I did one more test. I was curious if the issue would go away if I shorten the floating point representation. And indeed, shortening the representation by just removing the last digit ("3") avoids the issue:

	static const float kValue = 3.14159265358979f;

	float4 main() : SV_TARGET0
	{
		return kValue;
	}

Produces the correct SPIRV representation:

	; SPIR-V
	; Version: 1.0
	; Generator: Khronos Glslang Reference Front End; 7
	; Bound: 17
	; Schema: 0
	               OpCapability Shader
	          %1 = OpExtInstImport "GLSL.std.450"
	               OpMemoryModel Logical GLSL450
	               OpEntryPoint Fragment %main "main" %_entryPointOutput
	               OpExecutionMode %main OriginUpperLeft
	               OpSource HLSL 500
	               OpName %main "main"
	               OpName %_entryPointOutput "@entryPointOutput"
	               OpDecorate %_entryPointOutput Location 0
	       %void = OpTypeVoid
	          %3 = OpTypeFunction %void
	      %float = OpTypeFloat 32
	    %v4float = OpTypeVector %float 4
	%float_3_14159274 = OpConstant %float 3.14159274
	         %12 = OpConstantComposite %v4float %float_3_14159274 %float_3_14159274 %float_3_14159274 %float_3_14159274
	%_ptr_Output_v4float = OpTypePointer Output %v4float
	%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
	       %main = OpFunction %void None %3
	          %5 = OpLabel
	               OpStore %_entryPointOutput %12
	               OpReturn
	               OpFunctionEnd

**Comment by johnkslang** [comment] 2018-07-26 18:01
Okay, this is a platform dependence on parsing a floating-point number.

**Comment by johnkslang** [comment] 2018-07-26 19:09
Details:

The longer number (with the last '3') triggers a slow path that uses the platform's native `std::istringstream` to parse the number. For some reason, its `fail()` method reports `true`.

The shorter number uses native glslang code to parse, which is working the same everywhere.

This could be happening because you are in Germany (I'm just guessing, apologies) and locale stuff is not working correctly. It's using `imbue(std::locale::classic())` to make '.' be the decimal point.

It's a crazy idea, but does it work right if you use the longer form of the number and use a comma "," instead of a period?  Or, change your locale to one that uses periods for decimal points?

**Comment by awefers** [comment] 2018-07-26 19:14
I am in the US and my locale is set to US English (and I never used a German locale setting on this machine), so that cannot be the issue.

**Comment by johnkslang** [comment] 2018-07-26 22:09
Having just built from TOT, if you're in a position to help out, see https://github.com/KhronosGroup/glslang/commit/561a43d2727b5e8bc071d832dcba1140d03ab2eb, now part of TOT. It might solve the problem, but the logic right there is the most likely place things are going wrong.

**Comment by awefers** [comment] 2018-07-26 22:43
Just tried TOT but it is still exposing the issue. I will take a look "PpScanner.cpp" ASAP.

**Comment by johnkslang** [comment] 2018-07-26 23:00
Great, thanks.

**Comment by awefers** [comment] 2018-07-26 23:38
What about using atof() for the slow path? Or that cause that an issue for one of your target platforms? I.e. 

	ppToken->dval = atof( ppToken->name );

That fixes the issue on macOS.

**Comment by awefers** [comment] 2018-07-27 01:00
strtof_l() might be a better choice for error checking and locale support, didn't try that tho.

**Comment by johnkslang** [comment] 2018-07-27 01:45
Seems Apple has a bug in its library.

atof() has locale problems. See https://github.com/KhronosGroup/glslang/issues/234.

It was pretty hard to find a solution that was simultaneously high accuracy, forcible to use "." for the decimal point without threading issues, and portable. It is unfortunate Apple's does not work.

Maybe we can have an OS-dependent switch, once having confidence in what the alternative is. Maybe just truncating the string.

**Comment by awefers** [comment] 2018-07-27 05:32
The issue did not occur prior to updating to SDK v1.1.77.0. I did not check the commit history, but was the method of parsing floating point numbers changed at some point prior to the release of that SDK version?

**Comment by johnkslang** [comment] 2018-07-27 17:01
If `strtof_l()` works in general for Mac platforms, we can put it in under an `#ifdef`.

**Comment by johnkslang** [comment] 2018-07-27 17:15
Note this line in the currently passing test:

```
double pi = 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679;
```

I will try a few things.

**Comment by johnkslang** [comment] 2018-07-27 17:48
It is correlated with the trailing "f": If the number is long, and there is a trailing "f", OS X gives an error. I'll workaround it in glslang.

**Comment by johnkslang** [comment] 2018-07-27 19:48
Would you mind checking one more time?

This is now theoretically fixed by removing number suffixes, to bypass OS X thinking 'f' means the number should be short.

Thanks.

**Comment by awefers** [comment] 2018-07-27 20:02
I just tried with master TOT and the issue is now fixed. Thank you!

**Closed** 2018-07-27 20:21 UTC
Labels: PP, bug, question
