### ISSUE TITLE
WorkGroupSize specialization does not work when gl_WorkGroupSize is not referenced in the shader.

### ISSUE THREAD

**Issue by James-Jones** [KhronosGroup/glslang#557] opened 2016-10-19 15:51 UTC
This shader does not decorate WorkgroupSize with SpecId when I think it should.

```
#version 450

layout(local_size_x_id = 18, local_size_y_id=10,local_size_z_id = 19) in;


void main()
{
    gl_NumWorkGroups;
}


                          Capability Shader
           1:             ExtInstImport  "GLSL.std.450"
                          MemoryModel Logical GLSL450
                          EntryPoint GLCompute 4  "main" 9
                          ExecutionMode 4 LocalSize 1 1 1
                          Source GLSL 450
                          Name 4  "main"
                          Name 9  "gl_NumWorkGroups"
                          Decorate 9(gl_NumWorkGroups) BuiltIn NumWorkgroups
                          Decorate 11 BuiltIn WorkgroupSize
           2:             TypeVoid
           3:             TypeFunction 2
           6:             TypeInt 32 0
           7:             TypeVector 6(int) 3
           8:             TypePointer Input 7(ivec3)
9(gl_NumWorkGroups):      8(ptr) Variable Input
          10:      6(int) Constant 1
          11:    7(ivec3) ConstantComposite 10 10 10
     4(main):           2 Function None 3
           5:             Label
                          Return
                          FunctionEnd
```

This shader works and WorkgroupSize is decorated with SpecId. The difference is that gl_WorkGroupSize is referenced by the shader, but that shouldn't be a required.

```
#version 450

layout(local_size_x_id = 18, local_size_y_id=10,local_size_z_id = 19) in;

void main()
{
    gl_WorkGroupSize;
}

                          Capability Shader
           1:             ExtInstImport  "GLSL.std.450"
                          MemoryModel Logical GLSL450
                          EntryPoint GLCompute 4  "main"
                          ExecutionMode 4 LocalSize 1 1 1
                          Source GLSL 450
                          Name 4  "main"
                          Decorate 7 SpecId 18
                          Decorate 8 SpecId 10
                          Decorate 9 SpecId 19
                          Decorate 11 BuiltIn WorkgroupSize
           2:             TypeVoid
           3:             TypeFunction 2
           6:             TypeInt 32 0
           7:      6(int) SpecConstant 1
           8:      6(int) SpecConstant 1
           9:      6(int) SpecConstant 1
          10:             TypeVector 6(int) 3
          11:   10(ivec3) SpecConstantComposite 7 8 9
     4(main):           2 Function None 3
           5:             Label
                          Return
                          FunctionEnd
```

**Comment by James-Jones** [comment] 2016-10-20 10:10
I think the problem is that in ParseHelper.cpp
    `workGroupSize->getWritableType().getQualifier().specConstant = true`
will not work in the reported case because getEditableVariable\makeEditable is used which does copyUp instead of copyUpDeferredInsert.

**Comment by johnkslang** [comment] 2016-10-28 06:03
SPIR-V variable declarations are triggered by static reference to the symbol, so at least at a high level, the issue is a shader with no static reference causes no SPIR-V declaration.

The "Linker Objects" part of the AST is meant to cover cases where at a link level globals variables matter, regardless of whether they were referenced in the shader proper.  I'll look at adding WorkgroupSize there in this path, so the settings are not lost.

**Comment by johnkslang** [comment] 2016-11-04 15:20
FYI, the root problem was a copy of the type being made into the "Linker Objects" before all type editing was done.  This was causing multiple minor quality issues, and I have a much cleaner method in the works to address all these at once.  It's been code reviewed, but needs a bit more testing.

**Comment by johnkslang** [comment] 2019-04-19 05:36
This has long been fixed, closing.

**Closed by johnkslang** 2019-04-19 05:36 UTC
Labels: GLSL/ESSL, SPIR-V, bug
