### ISSUE TITLE
HLSL: return types on vertex shaders don't produce correct SPIRV

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#480] opened 2016-08-25 00:01 UTC
These should both be approximately similar code, but the second one produces what looks like wrong SPIRV (and fails the validator)

(assumed) Correct SPIRV:
```
struct VSOut
{
    float4 Pos : SV_Position;
    float2 Tex : location0;
};

VSOut main(uint vid : SV_VertexID, out VSOut Output ) 
{ 
    Output.Tex = 0; 
    Output.Pos = 1;
} 
```

(assumed failed, as fails validation) SPIRV
```
struct VSOut
{
    float4 Pos : SV_Position;
    float2 Tex : location0;
};

VSOut main(uint vid : SV_VertexID ) 
{ 
    VSOut Output;
    Output.Tex = 0; 
    Output.Pos = 1;
    return Output;
} 
```

**Comment by redorav** [comment] 2016-08-26 18:27
Right, thanks for looking into it. I'll monitor the bug and test once fixed.

**Comment by johnkslang** [comment] 2016-08-28 23:28
This is now known as a duplicate of #487 (well this one was first, but there is more up-to-date discussion in the other one).

**Closed by johnkslang** 2016-08-28 23:28 UTC
Labels: bug, duplicate, HLSL
